version: '3.8'

services:
  mysql_server:
    container_name: mysql_server
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # volumes: 
    #   - /app/node_modules
    #   - .:/app
    # depends_on:
    #   - mysql_server